name: Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 #v6.0.0
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c #v5
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@e7fa5ac41e1cf5b7d48e45e42232ce7ada589601 #v9.1.0
        with:
          version: latest
          only-new-issues: true

  super-linter-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 #v6.0.0

      - name: Super-linter
        uses: super-linter/super-linter@2bdd90ed3262e023ac84bf8fe35dc480721fc1f2 #v8.2.1
        env:
          DEFAULT_BRANCH: 'main'
          VALIDATE_MARKDOWN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  reviewdog-misspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 #v6.0.0
      - name: misspell
        uses: reviewdog/action-misspell@d6429416b12b09b4e2768307d53bef58d172e962 #v1.27.0
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"

  reviewdog-alex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 #v6.0.0
      - uses: reviewdog/action-alex@6083b8ca333981fa617c6828c5d8fb21b13d916b #v1.16.0

  goreportcard:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Go report card
        run: |
          path=$(curl -sf -X POST -F "repo=github.com/$GITHUB_REPOSITORY" https://goreportcard.com/checks | jq -r '.redirect')
          echo -e "\nSee report for https://goreportcard.com${path}"
