name: Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a #v5
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 #v6.1.1
        with:
          version: latest
          only-new-issues: true

  super-linter-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Super-linter
        uses: super-linter/super-linter@85f7611e0f7b53c8573cca84aa0ed4344f6f6a4d #v7.2.1
        env:
          DEFAULT_BRANCH: 'main'
          VALIDATE_MARKDOWN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  reviewdog-misspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: misspell
        uses: reviewdog/action-misspell@18ffb61effb93b47e332f185216be7e49592e7e1 #v1.26.1
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"

  reviewdog-alex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - uses: reviewdog/action-alex@986cf7dd82e702f82b4173deaa793a849f5b719d #v1.15.0

  goreportcard:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Go report card
        run: |
          path=$(curl -sf -X POST -F "repo=github.com/$GITHUB_REPOSITORY" https://goreportcard.com/checks | jq -r '.redirect')
          echo -e "\nSee report for https://goreportcard.com${path}"
