name: Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
    contents: read

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 #v5
        with:
          go-version-file: go.mod
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@a4f60bb28d35aeee14e6880718e0c85ff1882e64 #v6.0.1
        with:
          version: latest
          only-new-issues: true

  super-linter-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7

      - name: Super-linter
        uses: super-linter/super-linter@88ea3923a7e1f89dd485d079f6eb5f5e8f937589 #v6.6.0
        env:
          DEFAULT_BRANCH: 'main'
          VALIDATE_MARKDOWN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  reviewdog-misspell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - name: misspell
        uses: reviewdog/action-misspell@278e1b3c7dd09d2827fa080919a40db73ccafe24 #v1.22.0
        with:
          github_token: ${{ secrets.github_token }}
          locale: "US"

  reviewdog-alex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      - uses: reviewdog/action-alex@95457e9fb31e708d898774ca8e25be56d0766e84 #v1.12.0

  goreportcard:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Go report card
        run: |
          path=$(curl -sf -X POST -F "repo=github.com/$GITHUB_REPOSITORY" https://goreportcard.com/checks | jq -r '.redirect')
          echo -e "\nSee report for https://goreportcard.com${path}"
